### ISSUE TITLE
Analogue of yworks.com

### ISSUE THREAD

**Issue by alexander-myltsev** [schauder/degraph#54]
yworks.com doesn't respond. What else can be used to view graphs?

**Comment by schauder** [comment]
High Alexander,
that's a bummer. Unfortunately there is currently no alternative to yed. I do plan on creating a html page as output, but that will take some serious time until it is ready for prime time.

Until then I can offer only two options:

a) there seem to be various download sites that offer yed. You can find them when googling for yworks download

b) wait until yworks.com is back up

**Comment by alexander-myltsev** [comment]
Is it legitimate to put yED distros at this project's releases?

**Comment by schauder** [comment]
from the yed licence: 

> No distribution is to be made of the Software by the Licensee. The Licensee may make one copy of the Software for backup purpose only.

:-(

**Comment by alexander-myltsev** [comment]
OK.

**Comment by schauder** [comment]
yworks.com is back up it seems

**Comment by alexander-myltsev** [comment]
It does.
