### ISSUE TITLE
Imports for static final Strings are ignored

### ISSUE THREAD

**Issue by Okeanos** [schauder/degraph#70]
Dependencies are ignored if only static final Strings from a class are used. The dependency is only listed if a class instance itself is required.

**Comment by schauder** [comment]
Thanks for trying Degraph and letting me know about issues.

What you describe results from two things:

1. Degraph analyzes Byte Code only, so the import itself is not visible to Degraph
2. The Java Compiler does not store references to Strings and primitive compile time constants but puts basically copies of the constants everywhere they are referenced. if you have code like

        class A {
              public static final String HW = "Hello World"
        }

        class B { 
              { System.out.println(A.HW) } 
        }
    The byte code of `B` actually does not contain a dependency to `A`.

There really is not much Degraph can do about this (except analyzing source code, which I won't)

See also: http://stackoverflow.com/questions/3524150/is-it-possible-to-disable-javacs-inlining-of-static-final-variables

**Comment by Okeanos** [comment]
That's interesting to know. Thanks for explaining the problem.

**Comment by schauder** [comment]
Won't fix.
