### ISSUE TITLE
Slicing errors

### ISSUE THREAD

**Issue by opensource21** [schauder/degraph#78]
I tried at [sze - degraph](https://github.com/opensource21/sze/tree/degraph) to [test](https://github.com/opensource21/sze/blob/b42d5cdd4ab8e8af7866cbf8aaa47f9bef067264/src/test/java/degraph/DependencyTest.java) functional slices. I meaning to check if functional components refers in the right order. 
I created slices with:
```
     withSlicing("dao", SZE_BASE_PACKAGE + "dao.api.(*).**").
     withSlicing("frontend", SZE_BASE_PACKAGE + "frontend.(*).**").
     withSlicing("model", SZE_BASE_PACKAGE + "model.(*).**").
     withSlicing("service", SZE_BASE_PACKAGE + "service.*.(*).**").
     allow("admin", "zeugnis", "zeugnisconfig", "stammdaten", "common")
```
So what I want to check that a zeugnis-config-frontend doesn't refer a zeugnis-service. 
Even if I violate this rule, I didn't get an error. If I change the code so that I get an error and then get a graph, the whole graph is a mess with really many nodes. So it looks like the slices are wrong. But I have no idea how to analyze such a situation. The configuration even in the stacktrace
`categories = dao UnnamedPattern(net.sf.sze.dao.api.(*).**), frontend UnnamedPattern(net.sf.sze.frontend.(*).**), model UnnamedPattern(net.sf.sze.model.(*).**), service UnnamedPattern(net.sf.sze.service.*.(*).**)
` looks perfectly fine to me.

It looks like a bug to me. So whats wrongs with this approach and how can I get a list of classes which are not in any slices and a list of slices which are mapped by the patterns?

**Comment by schauder** [comment]
Sorry for the late reply. 

With the code you provide you create multiple **slicings**, but what you seem to intend is to create **one slicing** with multiple slices.

Without actually looking at your project the following change should get you in the right direction:

     withSlicing("functional", // the slicing name 
         SZE_BASE_PACKAGE + "dao.api.(*).**", //find the slice name for daos
         SZE_BASE_PACKAGE + "frontend.(*).**", //find the slice name for frontend code
         SZE_BASE_PACKAGE + "model.(*).**",
         SZE_BASE_PACKAGE + "service.*.(*).**").
         allow("admin", "zeugnis", "zeugnisconfig", "stammdaten", "common")

The unwiedly amount of nodes comes from the fact that for each slicing (4 in your previous code) each package that doesn't match any of the patterns, creates it's own node.

**Comment by opensource21** [comment]
Thanks for the information. Now it works. It was terrific to see how the rules helps to improve the code quality. Suddenly a common-package pops up and yes it has no clean target.
However it would be  good if the slicing-mechanism would be more transparent. More logs could be one approach or better documentation. Perhaps it would be good start to add to the documentation, that more than one withSlicing isn't useful in most usecases..

**Comment by schauder** [comment]
Great to hear, that it helped. And I agree: more logging could improve the usability quite a bit. I'll open a separate issue for that.
