### ISSUE TITLE
Possibility to check that a specific slice has no incoming/outgoing dependencies

### ISSUE THREAD

**Issue by FrVaBe** [schauder/degraph#83]
Is there a (simple) way to do checks like

- nothing (no other slice) should depend on a specific slice
- a specific slice should have no dependencies on any other slices

E.g. I want to check that nothing depends on my "gui" slice or that the "util" slice has no dependencies on other slices.

At the moment it only seems possible using the `allow` method and list all slices in a specific order (having the _specific_ slice of interest either in front or at the end of that list). I would like to do that without listing all slices.

Im interested in a Java DSL solution, by the way ;-)

**Comment by schauder** [comment]
Sorry for the late reply.

No, this is currently not possible.

**Comment by schauder** [comment]
This would become possible if Degraph would use Matchers (either existing ones from Hamcrest, AssertJ or an own implementation) instead of Strings.

**Comment by FrVaBe** [comment]
OK. Thanks anyway.
