### ISSUE TITLE
Multiple patterns per slice?

### ISSUE THREAD

**Issue by mattiasbertilsson** [schauder/degraph#86]
Is there a way to specify multiple package patterns for a named slice?

The use case is that I have 81 projects, containing 495 packages in total, with 4786 classes distributed among them. I would like to get a chart of the projects and their dependencies. Being able to expand and drill down to packages and classes would be nice, but is not a must. The project package structure is often well behaved, with a single unique common top level for each project, but far from always. This means I have to specify more than one package name pattern for each project slice, but neither repeating the project name with a new pattern (`projects = { projectA packageA.** projectA packageB.** ... }`), nor comma separating patterns (`projects = { projectA = packageA.**,packageB.** }`) seems to work.

**Comment by schauder** [comment]
repeating the name with the pattern *should* work. Can you please try again and post a complete configuration file if it doesn't?
