### ISSUE TITLE
IllegalArgumentException vs. log4j2

### ISSUE THREAD

**Issue by MichaelCkr** [schauder/degraph#88]
Hi Jens,

thanks for this tool. Very nice for unittests.

But now I got a problem, Stacktrace:

```
java.lang.IllegalArgumentException
	at de.schauderhaft.degraph.analysis.asm.Analyzer$.de$schauderhaft$degraph$analysis$asm$Analyzer$$analyze$1(Analyzer.scala:40)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:51)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1$$anonfun$apply$1.apply(Analyzer.scala:50)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:50)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$$anonfun$analyze$1.apply(Analyzer.scala:47)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at de.schauderhaft.degraph.analysis.asm.Analyzer$.analyze(Analyzer.scala:47)
	at de.schauderhaft.degraph.configuration.Configuration.createGraph(Configuration.scala:26)
	at de.schauderhaft.degraph.check.Check$$anon$1.apply(Check.scala:56)
	at de.schauderhaft.degraph.check.Check$$anon$1.apply(Check.scala:53)
	at de.schauderhaft.degraph.check.hamcrest.HamcrestWrapper.matchesSafely(HamcrestWrapper.scala:8)
	at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
	at org.hamcrest.core.Is.matches(Is.java:27)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:12)
	at org.b2bbp.functions.DependencyTest.testDependencies(DependencyTest.java:17)
```

I added the unitests for dependency-cycles some months ago and they work perfect. Now I tried to change our log4j-version to log4j2 (2.10.0). Result is the stacktrace above.

I thougth of the usual asm-problem, but the dependency hierarchy (maven) shows no other asm-version than the version 5.1 used by degraph. I excluded all other asm-Versions while introducing degraph.

Do you have any other advices how I can proceed? Perhaps any experince with log4j2?

Thanks, best regards,

Michael Ecker

**Comment by schauder** [comment]
I have never seen this. 
A wild guess is: Degraph was build pre java 8 so this might be that it (or the asm version it uses) can't handle Java 8 byte code?

Anyway. If you have a simple repo reproducing the issue I'd take a look.

**Comment by MichaelCkr** [comment]
Hi Jens,

I sent you an email to 'jschauder@pivotal.io'.

Best,


Michael Ecker
Sie finden uns auf der E-World am 6.-8.2. in Halle 7, Stand 7-212.
http://www.next-level-integration.com/e-world

Save the Date: Anwendertreffen 2018: 5+6. Juni in Köln
http://www.next-level-integration.com/anwendertreffen

Unsere News finden Sie unter
http://www.next-level-integration.com/news/
Next Level Integration GmbH
Nattermannallee 1
50829 Köln
fon +49 221 5898 280
fax +49 700 6556 7337
mecker@next-level-integration.com<mailto:mecker@next-level-integration.com>
http://www.next-level-integration.com<http://www.next-level-integration.com/>
------------------------------------------------
Amtsgericht Köln HRB 83305
Geschäftsführer: Dr. Stefan Klose, Andreas Pöhner

Von: Jens Schauder [mailto:notifications@github.com]
Gesendet: Donnerstag, 25. Januar 2018 16:18
An: schauder/degraph <degraph@noreply.github.com>
Cc: Ecker, Michael, NLI <mecker@next-level-integration.com>; Author <author@noreply.github.com>
Betreff: Re: [schauder/degraph] IllegalArgumentException vs. log4j2 (#88)


I have never seen this.
A wild guess is: Degraph was build pre java 8 so this might be that it (or the asm version it uses) can't handle Java 8 byte code?

Anyway. If you have a simple repo reproducing the issue I'd take a look.

**Comment by schauder** [comment]
@MichaelCkr didn't receive any mail. Spam folder is empty as well.

**Comment by MichaelCkr** [comment]
Then I’ll give it another trial here, I sent the attached mail with the attached maven module.


Michael Ecker
Sie finden uns auf der E-World am 6.-8.2. in Halle 7, Stand 7-212.
http://www.next-level-integration.com/e-world

Save the Date: Anwendertreffen 2018: 5+6. Juni in Köln
http://www.next-level-integration.com/anwendertreffen

Unsere News finden Sie unter
http://www.next-level-integration.com/news/
Next Level Integration GmbH
Nattermannallee 1
50829 Köln
fon +49 221 5898 280
fax +49 700 6556 7337
mecker@next-level-integration.com<mailto:mecker@next-level-integration.com>
http://www.next-level-integration.com<http://www.next-level-integration.com/>
------------------------------------------------
Amtsgericht Köln HRB 83305
Geschäftsführer: Dr. Stefan Klose, Andreas Pöhner

Von: Jens Schauder [mailto:notifications@github.com]
Gesendet: Freitag, 26. Januar 2018 10:20
An: schauder/degraph <degraph@noreply.github.com>
Cc: Ecker, Michael, NLI <mecker@next-level-integration.com>; Mention <mention@noreply.github.com>
Betreff: Re: [schauder/degraph] IllegalArgumentException vs. log4j2 (#88)


@MichaelCkr<https://github.com/michaelckr> didn't receive any mail. Spam folder is empty as well.

**Comment by MichaelCkr** [comment]
I uploaded it here:
https://download.next-level-apps.com/PublicDL/TEMP/MEC/

**Comment by MichaelCkr** [comment]
Log4j2 has a transitive dependency on asm in version 5.0.3 with scope test.
https://logging.apache.org/log4j/2.0/log4j-core/dependencies.html

com.google.code.java-allocation-instrumenter:java-allocation-instrumenter:jar:3.0.1 (test) [Information]
org.ow2.asm:asm:jar:5.0.3 (test) [Information]
[...]

com.google.code.java-allocation-instrumenter in Version 3.1.0 has asm in version 6.0 as dependency.

Now I'm thinking of the best way to get my problem solved. excluding the old asm-dependency from log4j doen't work.

best, Michael

**Comment by MichaelCkr** [comment]
Increasing my asm-Version from 5.1 to 6.0 with scope test seems to work. Don't know why.
